blog1/urls.py
from django.urls import path
from . import views

app_name = 'blog1'

urlpatterns = [
    path("", views.post_list, name="post_list"),
]

instagram1/urls.py
from django.urls import path, re_path, register_converter
from . import views
from .converters import YearConverter, MonthConverter, DayConverter

# url reverse에서 name space 역할
app_name = 'instagram1'

register_converter(YearConverter, 'year')
register_converter(MonthConverter, 'month')
register_converter(DayConverter, 'day')

urlpatterns = [
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),

    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),

    # re_path(r'(?P<pk>\d+)/$', views.post_detail)
    # path('archives/<int:year>/', views.archives_year),
    # re_path(r'archives/(?P<year>\d{4})/', views.archives_year),
    # re_path(r'archives/(?P<year>20\d{2})/', views.archives_year)
    path('archives/<year:year>/', views.archives_year),
    path('archive/', views.post_archive, name='post_archive'),
    path('archive/<year:year>/', views.post_archive_year, name='post_archive_year'),
    # path('archive/<year:year>/<month:month>/', views.post_archive_month, name='post_archive_month'),
    # path('archive/<year:year>/<month:month>/<day:day>/', views.post_archive_day, name='post_archive_day')
] 

learning/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='root.html'), name='root'),
    path('', RedirectView.as_view(
        # url='/instagram1/'
        pattern_name='instagram1:post_list'
    ), name='root'),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("blog1/", include("blog1.urls")),
    path("instagram1/", include("instagram1.urls")),
]    

# DEBUG=TRUE일 때 추가
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

# settings.MEDIA_URL
# settings.MEDIA_ROOT

instagram1/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import MinLengthValidator

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tag_set = models.ManyToManyField('Tag', blank=True)
    message = models.TextField(
        validators=[MinLengthValidator(10)]
    )
    photo = models.ImageField(blank=True, upload_to="instagram1/post/%Y/%m/%d")
    is_public = models.BooleanField(default=False, verbose_name="공개여부")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Java의 toString 기능
    def __str__(self):
        return f"Custom Post object ({self.id})"
        # return self.message

    def get_absolute_url(self):
        return reverse("instagram1:post_detail", kwargs={"pk": self.pk})
    

    class Meta:
        ordering = ["-id"]

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)    # post_id 필드 생성
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    # post_set = models.ManyToManyField(Post)

    def __str__(self):
        return self.name

instagram1/forms.py
import re

from django import forms
from  .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ['message', 'tag_set', 'photo', 'is_public']

    def clean_message(self):
        message = self.cleaned_data.get('message')
        if message:
            message = re.sub(r'[a-zA-Z]+', '', message)
        return message

instagram1/views.py
from typing import Any
from django.db import models
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.http import HttpResponse, HttpRequest, Http404
from django.views.generic import DetailView, ListView, ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView, DateDetailView, CreateView, FormView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from .forms import PostForm
from django.urls import reverse, reverse_lazy

# Create your views here.
# @login_required
# def post_new(request):
#     # POST 요청일 때
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user      # 현재 로그인된 user instance
#             form.save()
#             messages.success(request, '포스팅을 저장했습니다.')
#             return redirect(post)
#     # GET 요청일 때
#     else:
#         form = PostForm()

#     return render(request, 'instagram1/post_form.html', {
#         'form': form,
#         'post': None
#     })

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.author
        messages.success(self.request, '포스팅을 저장했습니다.')
        return super().form_valid(form)
    
post_new = PostCreateView.as_view()

# @login_required
# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)

#     # 작성자 Check Tip
#     if post.author != request.user:
#         messages.error(request, '작성자만 수정할 수 있습니다.')
#         return redirect(post)

#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             post = form.save()
#             messages.success(request, '포스팅을 수정했습니다.')
#             return redirect(post)
#     else:
#         form = PostForm(instance=post)

#     return render(request, 'instagram1/post_form.html', {
#         'form': form,
#         'post': post

#     })

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        messages.success(self.request, '포스팅을 수정했습니다.')
        return super().form_valid(form)
    
post_edit = PostUpdateView.as_view()

# @login_required
# def post_delete(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     if request.method == "POST":
#         post.delete()
#         messages.success(request, '포스팅을 삭제했습니다.')
#         return redirect('instagram1:post_list')
#     return render(request, 'instagram1/post_confirm_delete.html', {
#         'post': post,
#     })

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('instagram1:post_list')

    # def get_success_url(self):
    #     return reverse('instagram1:post_list')
    
post_delete = PostDeleteView.as_view()

def post_list(request):
    qs = Post.objects.all()
    # 결과 없으면 ''
    q = request.GET.get("q", "")

    if q:
        qs = qs.filter(message__icontains=q)

    # instagram1/templates/instagram1/post_list.html
    return render(
        request,
        "instagram1/post_list.html",
        {
            "post_list": qs,
            'q': q,
        },
    )

# post_list = ListView.as_view(model=Post, paginate_by=10)

# @method_decorator(login_required, name='dispatch')
# class PostListView(ListView):
#     model = Post
#     paginate_by = 10

# post_list = PostListView.as_view()

# def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
#     post = get_object_or_404(Post, pk=pk)
#     # DoesNotExist 예외 발생
#     # try:
#     #     post = Post.objects.get(pk=pk)
#     # except Post.DoesNotExist:
#     #     raise Http404
#     return render(request, 'instagram1/post_detail.html', {
#         'post': post,
#     })

class PostDetailView(DetailView):
    model = Post

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            qs = qs.filter(is_public=True)
        return qs

post_detail = PostDetailView.as_view(model=Post)

def archives_year(request, year):
    return HttpResponse(f"{year}년 archives")

post_archive = ArchiveIndexView.as_view(model=Post, date_field='created_at', paginate_by=10)
post_archive_year = YearArchiveView.as_view(model=Post, date_field='created_at')
post_archive_month = MonthArchiveView.as_view(model=Post, date_field='created_at')
post_archive_day = DayArchiveView.as_view(model=Post, date_field='created_at')

instagram1/templates/instagram1/layout.html
{% extends 'layout.html' %}

instagram1/templates/instagram1/post_archive.html
<h2>LASTEST</h2>
{{latest}}
<h2>date_list</h2>
{% for date in date_list %}
    {{ date|date:"Y" }}
{% endfor %}

instagram1/templates/instagram1/post_archive_year.html
<h2>YEAR</h2>
{{ year }} 

<h2>previous_year</h2>
{{ previous_year }} 

<h2>next_year</h2>
{{ next_year }}

<h2>date_list</h2>
{{ date_list }}

<h2>object_list</h2>
{{ object_list }}

instagram1/templates/instagram1/post_confirm_delete.html
{% extends 'instagram1/layout.html' %} {% block content %}
<form action="" method="post">
  {% csrf_token %}

  <div class="alert alert-danger">정말 삭제하시겠습니까?</div>

  <a href='{{ post.get_absolute_url }}' class='btn btn-secondary'>
    취소
  </a>
  <input type="submit" value="삭제" class="btn btn-danger" />
</form>
{% endblock content %}

instagram1/templates/instagram1/post_detail.html
{% extends "instagram1/layout.html" %}

{% block title %}
    Post Detail pk#{{ post.pk }}
{% endblock title %}

{% block content %}
    <h2>Author: {{ post.author }}</h2>

    {% if post.photo %}
        <div>
            <img src="{{ post.photo.url }}" />
        </div>
    {% endif %}

    {{ post.message|linebreaks }}
    <hr>
        <a href="{% url 'instagram1:post_list' %}" class="btn btn-primary">
            목록
        </a>
        <a href="{% url 'instagram1:post_edit' post.pk %}" class="btn btn-info">
            수정
        </a>
        <a href="{% url 'instagram1:post_delete' post.pk %}" class="btn btn-danger">
            삭제
        </a>
    </hr>
{% endblock content %}

instagram1/templates/instagram1/post_form.html
{% extends 'instagram1/layout.html' %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% comment %} <table>
            {{ form }}
        </table> {% endcomment %}
        {% buttons %}
            {% comment %} <input type="submit" value="저장" /> {% endcomment %}
            <button class='btn btn-primary'>
                저장
            </button>
        {% endbuttons %}
    </form>

    <hr/>

    {% if post %}
        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">
            내용으로
        </a>
    {% endif %}
    <a href="{% url 'instagram1:post_list' %}" class="btn btn-primary">
        목록
    </a>

{% endblock %}

instagram1/templates/instagram1/post_list.html
{% extends "instagram1/layout.html" %}
{% load bootstrap4 %}

{% block title %}
    INSTAGRAM / Post List
{% endblock title %}

{% block content %}
    <form action="" method="get">
        <input type="text" name="q" value="{{q}}"/>
        <input type="submit" value="검색"/>
    </form>

    <a href="{% url "instagram1:post_new" %}" class="btn btn-primary btn-block mt-3 mb-3">
        새 포스팅
    </a>

    <table class="table table-bordered table-hover">
        <tbody>
            {% for post in post_list %}
                <tr>
                    <td>
                        {{post.pk}}
                    </td>
                    <td>
                        {% if post.photo %}
                            <img src="{{post.photo.url}}" style="width: 100px;"/>
                        {% else %}
                            NO PHOTO
                        {% endif %}
                    </td>
                    <td>
                        {% comment %} <a href="{% url 'instagram1:post_detail' post.pk %}"> {% endcomment %}
                        <a href="{{ post.get_absolute_url}}">
                            {{post.message}}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
        {% bootstrap_pagination page_obj size='small' justify_content='center' %}
    {% endif %}
{% endblock content %}